name: Upload APK to GitHub

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  upload-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
